// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char DEVICE_LOGIN_NAME[]  = "1e1317a3-c58e-48ad-98ba-7f12edb53efc";

const char SSID[]               = SECRET_SSID;    // Network SSID (name)
const char PASS[]               = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)
const char DEVICE_KEY[]  = SECRET_DEVICE_KEY;    // Secret device password

void onS1Change();
void onS2Change();
void onS3Change();
void onS4Change();
void onS5Change();

bool s1;
bool s2;
bool s3;
bool s4;
bool s5;

void initProperties(){

  ArduinoCloud.setBoardId(DEVICE_LOGIN_NAME);
  ArduinoCloud.setSecretDeviceKey(DEVICE_KEY);
  ArduinoCloud.addProperty(s1, READWRITE, ON_CHANGE, onS1Change);
  ArduinoCloud.addProperty(s2, READWRITE, ON_CHANGE, onS2Change);
  ArduinoCloud.addProperty(s3, READWRITE, ON_CHANGE, onS3Change);
  ArduinoCloud.addProperty(s4, READWRITE, ON_CHANGE, onS4Change);
  ArduinoCloud.addProperty(s5, READWRITE, ON_CHANGE, onS5Change);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
