#include "arduino_secrets.h"
/* 
  Sketch generated by the Arduino IoT Cloud Thing "Untitled"
  https://create.arduino.cc/cloud/things/df7de480-a775-4fc6-9969-d6a8d19b8370 

  Arduino IoT Cloud Variables description

  The following variables are automatically generated and updated when changes are made to the Thing

  bool s1;
  bool s2;
  bool s3;
  bool s4;
  bool s5;

  Variables which are marked as READ/WRITE in the Cloud Thing will also have functions
  which are called when their values are changed from the Dashboard.
  These functions are generated with the Thing and added at the end of this sketch.
*/

#include "thingProperties.h"

void setup() {
  // Initialize serial and wait for port to open:
  Serial.begin(9600);
  // This delay gives the chance to wait for a Serial Monitor without blocking if none is found
  delay(1500); 

  // Defined in thingProperties.h
  initProperties();

  // Connect to Arduino IoT Cloud
  ArduinoCloud.begin(ArduinoIoTPreferredConnection);
  
  /*
     The following function allows you to obtain more information
     related to the state of network and IoT Cloud connection and errors
     the higher number the more granular information you’ll get.
     The default is 0 (only errors).
     Maximum is 4
 */
  setDebugMessageLevel(2);
  ArduinoCloud.printDebugInfo();
}

void loop() {
  ArduinoCloud.update();
  // Your code here 
  
  
}



/*
  Since S1 is READ_WRITE variable, onS1Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onS1Change()  {
  // Add your code here to act upon S1 change
}

/*
  Since S2 is READ_WRITE variable, onS2Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onS2Change()  {
  // Add your code here to act upon S2 change
}

/*
  Since S3 is READ_WRITE variable, onS3Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onS3Change()  {
  // Add your code here to act upon S3 change
}

/*
  Since S4 is READ_WRITE variable, onS4Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onS4Change()  {
  // Add your code here to act upon S4 change
}

/*
  Since S5 is READ_WRITE variable, onS5Change() is
  executed every time a new value is received from IoT Cloud.
*/
void onS5Change()  {
  // Add your code here to act upon S5 change
}